## Vendra Store

The `misaf/vendra-store` package owns the **ecommerce Store domain**: the concrete tenant model, its domains, and its storefront lifecycle. A Store *is* the tenant (`Models\Store implements Misaf\VendraTenant\Contracts\TenantContract`) — there is no separate tenant row and no `Store -> Tenant` hop. It decides when a store's storefront should be deployed, started, stopped, or destroyed, and what it should contain. It does not decide how a runtime is made to agree — that is an adapter's job.

### Translatable Persistence

- Making a persisted model field translatable is an explicit domain choice unless this package already requires it.
- Every field listed in a model's `$translatable` array must definitely use a JSON database column. Keep its model traits/casts, factories, validation, Filament locale UI, API serialization, and tests translation-aware.
- A field not listed in `$translatable` must use the appropriate scalar database type and must not use Spatie Translatable, translatable slug traits, locale switchers, translated callbacks, or translation-shaped array data.

### Vendra Transitive API Policy

- Treat a Vendra dependency intentionally exposed through the public API of a directly required Vendra platform package as part of the supported public contract of that package.
- Do not add a redundant direct Composer requirement solely because source code imports a type from that exposed dependency.
- Apply this only to Vendra platform packages listed under `require`; never extend it to `require-dev`, `suggest`, incidental implementation dependencies, or third-party packages. Removing or replacing an exposed dependency is a breaking change; keep `self.version` alignment across the Vendra package graph.

- Keep store and storefront code inside `packages/vendra-store` using the `Misaf\VendraStore` namespace.
- `Models\Store` is the application's tenant, wired through `config/vendra-tenant.php` (`model`, `relation`) and `config/multitenancy.php` (`tenant_model`, `tenant_finder`). `Store::accessible()` is the request-serving boundary — active, provisioning-ready, not billing-suspended — and both `StoreDomainFinder` and the resolver's search options go through it.
- A store's condition lives in three columns written by three concerns — `provisioning_status`, `active`, `billing_suspended_at`. `Store::status()` derives the single `Enums\StoreStatus` reading (Pending, Provisioning, Active, Suspended, Failed) and `Store::scopeWithStatus()` is that same rule as SQL. Never persist a status column beside them, and keep the accessor and the scope in step.
- `stores.locale`/`timezone` reach the tenancy engine through `TenantContract::getTenantLocale()`/`getTenantTimezone()`, never by the engine naming a Store; blank or null means "keep the platform's". `stores.currency` is read through `resolvedCurrency()` and falls back to `money.defaultCurrency`. `stores.metadata` is a free-form platform annotation bag — anything the platform queries earns a column instead. Store *settings* are the tenant-scoped `spatie/laravel-settings` rows, not a column here.
- Two ownership columns, two mechanisms, and they must not be confused. Reusable domain packages own their rows through the **neutral `tenant_id`** and `Misaf\VendraSupport\Tenancy\BelongsToTenant`; records that describe the Store itself (`store_domains`, `storefront_deployments`) carry **`store_id`** and use this package's `Concerns\BelongsToStore` / `Scopes\StoreScope`. Never add `store_id` to a reusable package's table, and never register a `store_id` table in the support `TenantTableRegistry`.
- `Services\StoreDomainFinder` is the adapter behind the engine's `Misaf\VendraTenant\Contracts\HostTenantFinder` port and the Spatie `tenant_finder`. Host-to-store mapping lives here, never in `misaf/vendra-tenant`.
- `Actions\ReplaceStoreDomainAction` normalizes and validates a replacement, soft-deletes the previous active domain as history, creates the new active domain inside the store's own tenant context, and moves the storefront with it — the deployment's `domain` in the same transaction, then a forced `ProvisionStorefrontJob`. A storefront is routed by a `Host()` rule in a container label and labels cannot be edited in place, so following the store to a new domain means replacing the container.
- Operator availability changes use `SuspendStoreAction` / `ReactivateStoreAction`; failed tenant provisioning recovery uses `RetryStoreProvisioningAction`. Storefront redeploy/retry use `RedeployStoreStorefrontAction` / `RetryFailedStorefrontDeploymentAction` and the existing jobs and transitions.
- `OffboardStoreAction` is the supported business removal path: require an audit reason, preserve prior state in metadata, inactivate, and soft-delete so observer-driven storefront shutdown and historical data retention remain intact. Restore only through `RestoreOffboardedStoreAction`, which revalidates ownership quota and provisioning readiness. Force deletion is infrastructure cleanup, not an operator workflow.
- `Contracts\StorefrontProvisioner` is the port to whatever actually runs a storefront. Every value crossing it is typed (`StorefrontProvisionRequest`, `StorefrontProvisionResult`, `StorefrontReference`, `StorefrontObservation`) — do not widen a method to an array parameter or return. Nothing on the interface mentions containers, because an implementation need not use them.
- `Services\ContainerStorefrontProvisioner` is the one implementation today, bound in `StoreServiceProvider::packageRegistered()`. It reaches the runtime only through `misaf/vendra-container`'s `ContainerRuntime`; callers type-hint the contract and must never branch on which adapter answered.
- Deleting a store settles its storefront, and that cascade lives in `Observers\StoreObserver` because there is no single delete path: the console table, the reseller table, and the reseller package's `OffboardResellerAction` all delete stores directly. A **soft delete** records `StorefrontDesiredState::Stopped` and queues `ReconcileStorefrontJob`, so restoring the store is a start rather than a redeploy; a **force delete** queues `DestroyStorefrontJob`, which is addressed by **slug** because the deployment row goes with the store's cascade before the worker runs. Never put this back into a delete path a caller has to remember to use.
- Convergence compares image *and* domain against what the container is actually labelled with. Both are fixed at creation, so both are drift only a replacement can fix; an unobserved value is not drift.
- Idempotence is contractual: `provision()` twice leaves one storefront, `start()` on a running one succeeds, `stop()` on a stopped one succeeds, `destroy()` on an absent one succeeds. Reconciliation and retry depend on this.
- `observe()` must never report "absent" for a runtime it could not reach — a converge pass would read that as a missing storefront and rebuild a healthy one.
- Status changes go through `StorefrontDeployment`'s `markProcessing()`/`markReady()`/`markRequested()`/`markFailed()`, which enforce the `Enums\StorefrontDeploymentStatus` transition table. Never `forceFill(['status' => ...])`. A job attempt that throws with retries left stays `Processing`; only `ProvisionStorefrontJob::failed()` writes `Failed`.
- The flow is `RequestStorefrontDeploymentAction` → `ProvisionStorefrontJob` → `StorefrontDeployment`; reconciliation and retry share `StorefrontDeploymentDispatchCommand`. Add a new entry point by reusing that flow, not by dispatching provisioning from a new place.
- `CreateStorePage` treats only an explicit `create_storefront=false` as an opt-out. The console wizard exposes that toggle and passes `optional: true` to storefront fields; reseller creation remains mandatory. Opting out creates the store and domain without a `StorefrontDeployment`.
- `Models\StorefrontImage` is the operator-managed catalog of approved immutable container references and their built-in themes. A deployment references one catalog row and provisioning/reconciliation use that row, never `STOREFRONT_IMAGE` or `STOREFRONT_THEMES` environment variables. Inactive images are unavailable for new deployments but remain valid for existing ones.
- Whether the platform is creating stores at all is `Settings\StoreCreationSettings` (group `store_creation`, `global` repository), read through `Support\StoreCreationPolicy`. Both panels that create stores consume the policy — the console as the whole gate, the reseller panel alongside the reseller's own subscription — which is what keeps `misaf/vendra-reseller` from ever pointing at `misaf/vendra-console`. Operators edit it on the console's platform settings page.
- Read every storefront setting through the injected `Support\StorefrontSettings` value object. It is bound with `bind()`, not `singleton()`, so a config change is picked up on the next resolve — keep it that way, and do not add `Config::get('vendra-store.*')` calls elsewhere.
- **This package must not depend on `misaf/vendra-reseller`.** The reseller domain sits above the store, so ownership arrives through `Contracts\StoreOwnerResolver` (default `Support\NullStoreOwnerResolver`, rebound by the reseller package) and store creation takes an owner typed `(Model&SubscriptionSubscriber)|null` — `ProvisionStoreAction::execute(..., ?SubscriptionSubscriber $owner = null)`, `CreateStorePage::resolveOwner()`. `stores.reseller_id` is a plain nullable indexed column with no cross-package foreign key; `$store->reseller()` and `$reseller->stores()` are both registered by `misaf/vendra-reseller`. `tests/ArchTest.php` enforces this.
- `Actions\AssignStoreOwnerAction` moves a store between billing owners, or to none. It names no reseller — the owner is a `SubscriptionSubscriber` and only `stores.reseller_id` records which one — and it takes the same row lock and `StoreQuota` check as creation, because a reassignment consumes a slot in the receiving plan. Re-selecting the owner a store already has is a no-op, never a quota failure.
- A null owner is not an error: it is a store the platform console owns directly. Quota checks go through `Support\StoreQuota`, which types its subscriber as `SubscriptionSubscriber` and is skipped entirely when there is no owner.
- Quota enforcement re-reads the owner under a row lock before counting; two concurrent creates would otherwise both pass the plan limit.
- This package ships shared Filament building blocks (`Filament\Pages\CreateStorePage`, `Filament\Schemas\StorefrontConfigurationFields`, `Filament\Actions\ReplaceDomainAction`, `Filament\Concerns\BuildsDailyTrend`), not panel resources — the console and reseller panels own those. If a resource is ever added here, one with a cluster lives in `src/Filament/Clusters/Resources/` and one without lives in `src/Filament/Resources/`.
- Follow Laravel comment style: document with PHPDoc (array shapes, generics, `@see`) and reserve inline comments for genuinely complex logic.
